### ISSUE TITLE
Can't target source_user in slack connector

### ISSUE THREAD

**Issue by drewpearce** [Legobot/Legobot#159]
You should be able to target source_user for a PM, however in Slack a PM has a unique channel id. See log snippet for reference. In this case I generated this log data from a PM with a legobot.

`2017-08-16 20:24:45,385 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Slack (urn:uuid:8b787bd1-cbab-4492-ae58-1282dc4480c9)
2017-08-16 20:24:45,385 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Crypto (urn:uuid:4b90fdd5-fa58-4ee2-af30-4f885968a1b9)
2017-08-16 20:24:45,386 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Help (urn:uuid:b45e3904-113d-47a7-a9ef-4e9756237448)
2017-08-16 20:24:45,387 - legos.cryptocurrency - DEBUG - {'text': '!help crypto', 'metadata': {'opts': None, 'source_channel': 'D43AFR58U', 'source': 'urn:uuid:8b787bd1-cbab-4492-ae58-1282dc4480c9', 'source_user': 'U039XH0R3', 'is_private_message': True, 'text': '!help crypto', 'dest': None}, 'should_log': False}`

**Comment by bbriggs** [comment]
I think the proper way to resolve is is to leave `source_user` as it is, but patch the slack connector to route replies to a user (assuming the prefix `U.*` is reliable) to resolve them to a private message channel.

**Comment by bbriggs** [comment]
This also makes me wonder how the Slack connector in its current state would handle a multi-user private message.

**Comment by drewpearce** [comment]
I was thinking the same thing. I assume the slack rtm client must have some way to resolve those channel names. same with multi-user pms.

**Comment by bbriggs** [comment]
According to the [RTM client's documentation](https://github.com/slackapi/python-slackclient#sending-a-message), you can use the user ID for a PM:
> To send a message to a channel, use the channel's ID. For IMs, use the user's ID.

**Comment by drewpearce** [comment]
when i set my lego to reply to message['metadata']['source_user']:

`2017-08-17 09:38:50,931 - legos.cryptocurrency - DEBUG - {'metadata': {'source_channel': 'C6P55JXEV', 'dest': None, 'source_user': 'U039XH0R3', 'opts': None, 'text': '!help crypto', 'source': 'urn:uuid:9b41340e-26fb-43b0-a841-d05a08d9fa38', 'is_private_message': False}, 'should_log': False, 'text': '!help crypto'}
2017-08-17 09:38:50,932 - Legobot.Lego - DEBUG - Acquired lock in cleanup for Slack (urn:uuid:9b41340e-26fb-43b0-a841-d05a08d9fa38)
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Users/drew/repos/Legobot/Legobot/Lego.py", line 30, in run
    self.handler(self.message)
  File "/Users/drew/repos/Legobot/Legobot/Connectors/Slack.py", line 192, in handle
    message=message['text'])
  File "/Users/drew/virtualenvs/legobot/lib/python3.5/site-packages/slackclient/_client.py", line 151, in rtm_send_message
    return self.server.channels.find(channel).send_message(
AttributeError: 'NoneType' object has no attribute 'send_message'`

**Comment by bbriggs** [comment]
so doing a lookup on `U039XH0R3` returned `None`. What about updating the pinned slackclient library? Can you tell what version you're currently on?

**Comment by drewpearce** [comment]
for documentation purposes, I updated the slackclient to the latest version and got the same issue, just with different line numbers.

**Comment by bbriggs** [comment]
This appears to be the section of the docs we are interested in:

```
Post to an IM channel
Posting to an IM channel is a little more complex depending on the value of as_user.

If as_user is false:
Pass a username (@chris) as the value of channel to post to that user's @slackbot channel as the bot.
Pass the IM channel's ID (D023BB3L2) as the value of channel to post to that IM channel as the bot. The IM channel's ID can be retrieved through the im.list API method.
If as_user is true:
Pass the IM channel's ID (D023BB3L2) as the value of channel to post to that IM channel as the authenticated user. The IM channel's ID can be retrieved through the im.list API method.
```

**Comment by drewpearce** [comment]
This doesn't work consistently. im.list doesn't return a full list of available users to dm. should be using im.open instead to get the channel id. See https://stackoverflow.com/questions/37598354/slack-dm-to-a-user-not-in-im-list
