### ISSUE TITLE
Slack RTM connection appears to be timing out

### ISSUE THREAD

**Issue by bbriggs** [Legobot/Legobot#164]
```
2017-08-17 20:48:41,705 - Legobot.Connectors.Slack - DEBUG - {'type': 'reconnect_url', 'url': 'wss://mpmulti-fek3.slack-msgs.com/websocket/lqblAe41gqd-p2XTUS6wYdApBO5OQ3fNo_LYYDwZ3riF5M5VV9KIuNTZh3LHDZdRlXk7xyXuWq1-QQlirCOdddA6S0v8cYCxgBqqxJi4jzYTmVlnrIqB10l0YJ0Da48-6UQOXpPJbYVQv1FymV0r41_zEsh1ZTZGny6EF_AXBp4='}
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/Legobot/Connectors/Slack.py", line 89, in run
    for event in self.slack_client.rtm_read():
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/slackclient/client.py", line 126, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/slackclient/server.py", line 155, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 288, in recv_header
    header = self.recv_strict(2)
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "/Users/bren/repos/personal/chatbots/legobot-stuff/Legobot/venv/lib/python3.6/site-packages/websocket/_socket.py", line 80, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 987, in recv
    return self.read(buflen)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 627, in read
    v = self._sslobj.read(len)
TimeoutError: [Errno 60] Operation timed out
```

**Comment by drewpearce** [comment]
Covered by #185
