### ISSUE TITLE
Connection Manager

### ISSUE THREAD

**Issue by drewpearce** [Legobot/Legobot#185]
Right now if a connection is interrupted, Legobot craps the bed and dies. Need better exits with the option to reconnect and progressively increasing intervals.
An option to attempt a notification of some sort isn't a bad idea either.

**Comment by drewpearce** [comment]
Example error:
```
2018-03-13 20:41:30,632 - Legobot.Connectors.Slack - DEBUG - {'type': 'goodbye'}
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/Legobot/Connectors/Slack.py", line 89, in run
    for event in self.slack_client.rtm_read():
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/slackclient/_client.py", line 123, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/slackclient/_server.py", line 141, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_core.py", line 293, in recv
    opcode, data = self.recv_data()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_core.py", line 310, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_core.py", line 323, in recv_data_frame
    frame = self.recv_frame()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_core.py", line 357, in recv_frame
    return self.frame_buffer.recv_frame()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_abnf.py", line 336, in recv_frame
    self.recv_header()
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_abnf.py", line 286, in recv_header
    header = self.recv_strict(2)
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_abnf.py", line 371, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_core.py", line 427, in _recv
    return recv(self.sock, bufsize)
  File "~/virtualenvs/legobot/lib/python3.5/site-packages/websocket/_socket.py", line 93, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

```

**Comment by drewpearce** [comment]
goodbye message: https://api.slack.com/events/goodbye

**Comment by bbriggs** [comment]
Now we know what to handle for graceful disconnects

**Comment by drewpearce** [comment]
Commit 96ad4fc05727e5482670e1e9b79eb339e6516812 was supposed to address this, but does not appear to do the job. If someone wants to tackle this, that would be great.
